/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_rogier_version_console;

import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Evan1204
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FenetreModeJeu
     */
    public FenetrePrincipale() {
        initComponents();
        //Affiche le message "Victore !"
        Bienvenue.setLayout(new GridLayout(1, 1));
        getContentPane().add(Bienvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 500, 100));
        this.pack();
        this.revalidate();

        JLabel labelBienvenue = new JLabel("Bienvenue sur LIGHTOFF !");
        labelBienvenue.setFont(new Font("SansSerif", Font.BOLD, 24)); // Ajustez la police selon vos préférences
        labelBienvenue.setHorizontalAlignment(JLabel.CENTER); // Centre le texte horizontalement
        labelBienvenue.setVerticalAlignment(JLabel.CENTER); // Centre le texte verticalement
        Bienvenue.add(labelBienvenue);
        
        //Affiche un bouton facile vers la grille facile
        Facile.setLayout(new GridLayout(1, 1));
        getContentPane().add(Facile, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, 40));
        this.pack();
        this.revalidate();

        JButton bouton_Facile = new JButton("Facile");
        ActionListener ecouteurClick1 = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
            FenetreFacile nouvelleFenetre = new FenetreFacile();
            nouvelleFenetre.setVisible(true);
            dispose();
            }
        };
        bouton_Facile.addActionListener(ecouteurClick1);
        Facile.add(bouton_Facile);
        
        //Affiche un bouton moyen vers la grille moyenne
        Moyen.setLayout(new GridLayout(1, 1));
        getContentPane().add(Moyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 80, 40));
        this.pack();
        this.revalidate();

        JButton bouton_Moyen = new JButton("Moyen");
        ActionListener ecouteurClick2 = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
            FenetreMoyen nouvelleFenetre = new FenetreMoyen();
            nouvelleFenetre.setVisible(true);
            dispose();
            }
        };
        bouton_Moyen.addActionListener(ecouteurClick2);
        Moyen.add(bouton_Moyen);
        
        //Affiche un bouton difficile vers la grille difficile
        Difficile.setLayout(new GridLayout(1, 1));
        getContentPane().add(Difficile, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 80, 40));
        this.pack();
        this.revalidate();

        JButton bouton_Difficile = new JButton("Difficile");
        ActionListener ecouteurClick3 = new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
            FenetreDifficile nouvelleFenetre = new FenetreDifficile();
            nouvelleFenetre.setVisible(true);
            dispose();
            }
        };
        bouton_Difficile.addActionListener(ecouteurClick3);
        Difficile.add(bouton_Difficile);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bienvenue = new javax.swing.JPanel();
        Facile = new javax.swing.JPanel();
        Moyen = new javax.swing.JPanel();
        Difficile = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienvenue.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout BienvenueLayout = new javax.swing.GroupLayout(Bienvenue);
        Bienvenue.setLayout(BienvenueLayout);
        BienvenueLayout.setHorizontalGroup(
            BienvenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        BienvenueLayout.setVerticalGroup(
            BienvenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(Bienvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 370, -1));

        Facile.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout FacileLayout = new javax.swing.GroupLayout(Facile);
        Facile.setLayout(FacileLayout);
        FacileLayout.setHorizontalGroup(
            FacileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        FacileLayout.setVerticalGroup(
            FacileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(Facile, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 170, 40));

        Moyen.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout MoyenLayout = new javax.swing.GroupLayout(Moyen);
        Moyen.setLayout(MoyenLayout);
        MoyenLayout.setHorizontalGroup(
            MoyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        MoyenLayout.setVerticalGroup(
            MoyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(Moyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 170, 40));

        Difficile.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout DifficileLayout = new javax.swing.GroupLayout(Difficile);
        Difficile.setLayout(DifficileLayout);
        DifficileLayout.setHorizontalGroup(
            DifficileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        DifficileLayout.setVerticalGroup(
            DifficileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(Difficile, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 170, 40));

        jLabel1.setText("Choisis ta difficulté :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 150, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bienvenue;
    private javax.swing.JPanel Difficile;
    private javax.swing.JPanel Facile;
    private javax.swing.JPanel Moyen;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
